### PR TITLE
Entries: mention 1.19.5 release

### PR DESCRIPTION
**Pull request by bytestream**

### CODE REVIEW

**Review by staabm — APPROVED** [review]
lgtm thanks.

I tested 2 links of the list and they seem to work as expected

**Comment by bytestream** [comment]
I think you'll need to deploy it for me?

**Comment by staabm** [comment]
yeah exactly. after merge I need to run the deployment

**Comment by bytestream** [comment]
@staabm updated to 1.19.5

**Comment by staabm** [comment]
Thanks

**Comment by staabm** [comment]
Deployed. Thank you @bytestream

**Pull request merged**
