### PR TITLE
Update to use cdn urls

### PR DESCRIPTION
**Pull request by Arkni**

### CODE REVIEW

**Comment by Arkni** [comment]
I reverted also the last commit (re-introducing Microsoft cdn urls)

**Comment by staabm** [comment]
@Arkni did you say that you will remove the "revert" commit? is this PR ready to land?

**Comment by Arkni** [comment]
Sorry, I'm mean, I reintroduced the Microsoft cdn links. So this PR is ready to land.

**Comment by staabm** [comment]
merged and deployed, thx

**Pull request merged**
